<a href="https://colab.research.google.com/github/MichelWakim/-making-a-neural-network-to-classify-3-types-of-flowers-using-4-features/blob/main/Classify%203%20types%20of%20flowers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#making a neural network to classify 3 types of flowers using 4 features

In [1]:
import numpy as np
from sklearn import datasets
from sklearn.preprocessing import OneHotEncoder #then encoding for differing the output neurons

In [2]:
iris = datasets.load_iris() #loading the dataset
#print(type.iris)

In [3]:
data = iris.data      #the data of the dataset
labels = iris.target  #getting the dataset labels  
print(data.shape)
print(labels.shape)

(150, 4)
(150,)


In [4]:
print(data[:5])   #printing all the data till row five 

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [5]:
encoder = OneHotEncoder()   #making a shortcut
y = encoder.fit_transform(labels[:,None]).toarray() #transforming the  zero rank array to 1D array using [:,None]
                                                      #encoding the labels in a form of an array
print(y)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x_train, x_test, y_train, y_test = train_test_split(data, y, test_size=0.25)  #x is the data 
                                                                              #this function splits the dataset randomly to test data and train data
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(112, 4)
(38, 4)
(112, 3)
(38, 3)


# `Building the NN`

In [8]:
from keras.models import Sequential #fror making the model in layers sequentially 
from keras.layers import Dense    #Dense is a layer in the NN

In [9]:
classifier = Sequential()
classifier.add(Dense(input_shape= (4,), units=8, activation='relu')) #relu is faster 
classifier.add(Dense(input_shape= (4,), units=8, activation='relu'))
classifier.add(Dense(units= 3,activation='softmax'))    #softmax is better than the sigmoind in the big data
classifier.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 8)                 40        
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


# `Training the model`

In [10]:
from keras.optimizers import Adam
adam=Adam(lr=0.05)  #adding the learning rate

classifier.compile(loss='categorical_crossentropy',
                   optimizer=adam,  #Ican change the opptimizer
                   metrics=['accuracy']) #can changing the metrics

In [11]:
history= classifier.fit(x_train, y_train,
               epochs=25,
               batch_size=10,)

Epoch 1/25
12/12 [==============================] - 0s 3ms/step - loss: 0.9650 - accuracy: 0.5714
Epoch 2/25
12/12 [==============================] - 0s 3ms/step - loss: 0.6125 - accuracy: 0.7054
Epoch 3/25
12/12 [==============================] - 0s 2ms/step - loss: 0.5318 - accuracy: 0.7054
Epoch 4/25
12/12 [==============================] - 0s 2ms/step - loss: 0.5004 - accuracy: 0.7054
Epoch 5/25
12/12 [==============================] - 0s 2ms/step - loss: 0.4840 - accuracy: 0.7054
Epoch 6/25
12/12 [==============================] - 0s 2ms/step - loss: 0.4733 - accuracy: 0.7054
Epoch 7/25
12/12 [==============================] - 0s 2ms/step - loss: 0.4690 - accuracy: 0.7054
Epoch 8/25
12/12 [==============================] - 0s 2ms/step - loss: 0.4660 - accuracy: 0.7054
Epoch 9/25
12/12 [==============================] - 0s 2ms/step - loss: 0.4638 - accuracy: 0.7054
Epoch 10/25
12/12 [==============================] - 0s 2ms/step - loss: 0.4624 - accuracy: 0.7054
Epoch 11/25
12/12 [

Testing the NN

In [12]:
score =classifier.evaluate(x_test,y_test)
print(score)      #prints the loss , the accuracy

2/2 [==============================] - 0s 3ms/step - loss: 0.5576 - accuracy: 0.5526
[0.5575864911079407, 0.5526315569877625]


In [13]:
print('Accuracy = {}%' .format(score[1]*100))

Accuracy = 55.263155698776245%
